[[materials]]
name = "P53"
filename = "P04637.fasta"
description = """
A FASTA file that contains a protein sequence of human tumor antigen protein p53.
"""

[[materials]]
name = "primes"
filename = "primes.dat"
description = """
The first 10,000 prime numbers.
"""
action = ["deserialize"]
build = """
using Primes
primes = Int[]
p = 1
while length(primes) < 10_000
    if isprime(p)
        push!(primes, p)
    end
    p += 1
end
open("primes.dat", "w") do out
    serialize(out, primes)
end
"""
